# Pytorch Demo

This notebook provides a working demo of Pytorch. It is based on official tutorials referenced below.

There are three main sections. First one reviews basics, second provides a skorch overview and third explains details of a broadcast based distributed example.

## Basics Review

In [6]:
import torch
import numpy as np

print( 'initialize from Python list of list' )
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)


print( '\ninitialize from NumPy array')
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_data)

print( '\ninitialize using builtin functions')
shape = (2,3,)
rand_tensor = torch.rand(shape)
print(rand_tensor)
ones_tensor = torch.ones(shape)
print(ones_tensor)
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

initialize from Python list of list
tensor([[1, 2],
        [3, 4]])

initialize from NumPy array
tensor([[1, 2],
        [3, 4]])

initialize using builtin functions
tensor([[0.5408, 0.1525, 0.6799],
        [0.5660, 0.9491, 0.9543]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
print('tensor attributes')
tensor = torch.rand(2,3)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

if torch.cuda.is_available():
  tensor = tensor.to('cuda')

tensor attributes
torch.Size([2, 3])
torch.float32
cpu


In [10]:
print('tensor indexing and slicing')
tensor = torch.ones(2,3)
tensor[:,1] = 0
print(tensor)

tensor indexing and slicing
tensor([[1., 0., 1.],
        [1., 0., 1.]])


In [12]:
print('element-wise product')
t1 = torch.ones(2,2)*2
t2 = torch.ones(2,2)*3
print(t1.mul(t2))
print(t1*t2)

element-wise product
tensor([[6., 6.],
        [6., 6.]])
tensor([[6., 6.],
        [6., 6.]])


In [14]:
print('matrix multiplication')
print(t1.matmul(t2))
print(t1 @ t2)

matrix multiplication
tensor([[12., 12.],
        [12., 12.]])
tensor([[12., 12.],
        [12., 12.]])


In [ ]:
autograd

In [ ]:
nn

## Skorch Overview

In [ ]:
main example

In [ ]:
grid search

## Broadcast Distributed Example

In [ ]:
https://github.com/cankav/pytorcher/blob/master/run_distributed_broadcast.py

In [ ]:
https://github.com/RyersonU-DataScienceLab/pomdp_solvers/blob/master/dist_utils/distributed_utils.py
    
    
    resim ile anlat
    

## References

* https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
* https://github.com/skorch-dev/skorch
* https://github.com/cankav/pytorcher
* https://github.com/RyersonU-DataScienceLab/pomdp_solvers/blob/master/dist_utils/distributed_utils.py